version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5713:5713"
    environment:
      - PORT=5713
      - MONGO_URI=mongodb://mongo:27017/storemate
      - JWT_SECRET=stormate_docker_secret_key_2026
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
